function [p, data] = biips_model(filename, data, varargin)
% BIIPS_MODEL instantiate a stochastic model under a DAG form 
% function p = biips_model(filename, data, [sample_data], [data_rng_seed], [quiet])
%  INPUT : 
%  - filename : name of the BUGS file which describes the stochastic model
%  - data : struct containing constants and observed values
%  - sample_data: boolean to choose if data is generated by the model
%  - rng_seed : data rng_seed 
%  - quiet : boolean to deactivate verbosity 

% check for optional options
opt_argin = length(varargin);
% defauts values
sample_data = true; 
if (~exist('OCTAVE_VERSION')) % check MATLAB/OCTAVE run
  s=rng('shuffle');
  data_rng_seed=randi(intmax);
  rng(s);
else
  % Octave version
  s=rand('state');
  rand('state',time);
  data_rng_seed=double(randi(intmax));
  rand('state',s);
end
quiet = false;

if opt_argin >= 1
   sample_data = varargin{1};
end
if opt_argin >=2 
   data_rng_seed = varargin{2};
end   

if opt_argin >=3
    quiet = varargin{3};
end    

% processing data argument
if (isa(data, 'cell'))
    data = reshape(data, length(data), 1);
    
    isch = cellfun(@(x) ischar(x), data);
    ignored_var = data(~isch);
    if (~isempty(ignored_var))
        warning('ignored non character elements in ''data'' cell argument.');
    end
    data = data(isch);
    
    isnum = cellfun(@(x) isnumeric(evalin('base', x)), data, 'ErrorHandler', @(S, varargin) false);
    ignored_var = data(~isnum);
    if (~isempty(ignored_var))
        varnames = sprintf('%s ',ignored_var{:});
        warning('ignored the following (either non numeric or non existent) variables given in ''data'' cell argument: %s ', varnames);
    end
    
    data = data(isnum);
    
    data = cell2struct(cellfun(@(x) evalin('base',x), data, 'UniformOutput', false), data, 1);
end

p = inter_biips('make_console');
if (quiet)
  inter_biips('verbosity', 0);
end

% load model and do some checks
inter_biips('check_model', p, filename);
inter_biips('compile_model', p, data, sample_data, data_rng_seed);
data = inter_biips('get_data', p);
