find_program(MATLAB matlab)
if (MATLAB)
   get_filename_component(MATLAB_BINDIR ${MATLAB} PATH)
   set(MEX_COMMAND ${MATLAB_BINDIR}/mex)
   if (EXISTS ${MEX_COMMAND})
      message (STATUS "mex (Matlab) found=" ${MEX_COMMAND})
      set(MEX_FOUND 1)
   endif(EXISTS ${MEX_COMMAND})
   execute_process(COMMAND ${MATLAB_BINDIR}/mexext OUTPUT_VARIABLE MEX_EXT)
   message(STATUS "mex extension on this machine =" ${MEX_EXT})
else(MATLAB)
  find_program(MKOCT mkoctfile)
  if(MKOCT)
    message (STATUS "mkoctfile (Octave) found =" ${MKOCT})
    set(MEX_FOUND 1)
    set(MEX_COMMAND ${MKOCT} --mex)
    set(MEX_EXT mex)
  else(MKOCT)
    message(STATUS "No Matlab or Octave mex compiler found") 
    set(MEX_FOUND 0)
  endif(MKOCT)
endif(MATLAB)
