find_program(MKOCT mkoctfile)
if(MKOCT)
    message (STATUS "(Octave) found : ${MKOCT}")
    set(MEX_FOUND OCTAVE)
    set(MEX_COMMAND ${MKOCT} --mex)
    set(MEX_EXT mex)
    find_program(OCTAVE "octave")
    if (OCTAVE)
        set(MATLAB_COMMAND "${OCTAVE}")
        set(MATLAB_FLAGS --traditional)
    endif(OCTAVE)	    
endif(MKOCT)    
