#first search for MATLAB

find_program(MATLAB matlab)
if (MATLAB)
   message (STATUS "MATLAB executable found=" ${MATLAB})
   get_filename_component(MATLAB_BINDIR ${MATLAB} PATH)
   set(MEX_COMMAND ${MATLAB_BINDIR}/mex)
   if (EXISTS ${MEX_FILE})
      message (STATUS "mex (MATLAB) found=" ${MEX_FILE})
      set(MEX_FOUND 1)
   endif(EXISTS ${MEX_FILE})
else(MATLAB)
  find_program(MKOCT mkoctfile)
  if(MKOCT)
    message (STATUS "mkoctfile found =" ${MKOCT})
    set(MEX_FOUND 1)
   set(MEX_COMMAND ${MKOCT} --mex)
  else(MKOCT)
    message(STATUS "No octave or Matlab found => no mex on your computer") 
    set(MEX_FOUND 0)
  endif(MKOCT)
endif(MATLAB)

